#!/bin/bash

API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

response=$(curl -s -w "%{http_code}" -o "$OUTPUT_FILE" "$API_URL"  )
status_code=${response: -3}

if [ "$status_code" -ne 200 ]; then
    echo "An error occured with the request with a status code: $status_code" >> "$ERROR_FILE"
fi

